version: 2.1
# Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
orbs:
  cypress: cypress-io/cypress@3.3.1

executors:
  cypress-executor:
    docker:
      - image: cypress/base:latest

jobs:
  start-server:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build

workflows:
  run-tests:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component